# Generated by Django 5.0.6 on 2024-06-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fare',
            field=models.FloatField(default=0),
        ),
    ]
