# Generated by Django 3.2.25 on 2024-06-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_car_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='park',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
