# Generated by Django 5.0.6 on 2024-06-09 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
from parking.models import ParkingInfo

from dotenv import load_dotenv
import os

load_dotenv()

def create_initial_superuser(apps, schema_editor):
    User.objects.create_superuser(
        username=os.getenv('SUPERUSER_USERNAME'),
        email=os.getenv('SUPERUSER_EMAIL'),
        password=os.getenv('SUPERUSER_PASSWORD'),
        )

def create_parkinginfo_record(apps, schema_editor):
    parkinfo = ParkingInfo()
    parkinfo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_car_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, null=True)),
                ('places', models.IntegerField(default=0)),
                ('limit', models.FloatField(default=0)),
                ('default_fare', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_parkinginfo_record),
        migrations.RunPython(create_initial_superuser),
    ]
