# Generated by Django 5.0.6 on 2024-06-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0005_parkinginfo_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ban",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
